### PR TITLE
Support for multiple prefixes

### PR DESCRIPTION
**Pull request by cleung2010**
Addresses issue https://github.com/hashicorp/consul-replicate/issues/3

### CODE REVIEW

**Comment by armon** [comment]
I don't think this will work as intended. The major issues are that there are new go routines being started on each iteration of the replicate loop instead of long running ones per src/dst. Also the "status" file needs to be modified to track the last index per (src/dst) pair, since the LastIndex value is dependent on the source prefix. I think replicate needs to be refactored to more sanely handle this.

**Comment by cleung2010** [comment]
Thanks for pointing that out, I'll work on that then.

**Comment by armon** [comment]
Sorry, let be clarify. 

1) In replicate.go#276 you are spawning a new goroutine for each prefix. Assume there is prefix {A, B, C}.
2) When a change happens, say to prefix A, the change is sent down and the outer function handles it
3) The LastReplicated is set to LastIndex of Prefix A
4) The loop returns to `WAIT`
5) At this point, we spawn new go routines again. This time there is a goroutine watching for {A, B, B, C, C}. The previously spawned watchers are still running, (except A), but now there are multiple. Worse, the new watchers for B and C are using the index value from A. You can repeat this example and end up with an arbitrary number of go routines running. This is what I mean.

The second issue has to do with the LastIndex not being distinct. Suppose the source datacenter is at the given index per prefix (A, 100) (B, 200) (C, 300). Suppose we replicate C last, and then crash (for whatever reason). When we restart, all the watchers will block for updates at A,B,C until the Index exceeds 300 (the LastReplicated value). However, there could have been updates to A and B that we haven't processed yet, such that they are now at (A, 150) (B, 250) (C, 300). In this case, consul-replicate won't catch those changes. This is why the LastReplicated Index must be kept distinct.

The goroutine is just silently masked, so it will work but it will be wasteful of resources. The second issue is hard to reproduce and only happens in racey failure conditions, not in the happy path.

**Comment by cleung2010** [comment]
Thanks for clarifying. I thought all goroutines from the first loop iteration would end since the channel received a signal from one of the three goroutines and all goroutines are using the same channel such that in the second iteration go routine would be watching for {A, B, C} again. 

I also thought, from what I observed, that the index is a global value in consul, so if we have (A, 100) (B, 200) (C, 300) and then a crash, the next time that A gets updated it will be (A, 301) (B, 200) (C, 300). In my test run, the index for web/key1 was 1040 so status.LastReplicated gets updated to 1040 in replicate.go#L338, and then the update to global/key1 gives that KV an index of 1043, so status.LastReplicated gets updated and the replication is processed.

**Comment by armon** [comment]
The go routines will be stuck in the KV.List() so they will still be running in the background. You are correct that the index is a global value in Consul, but there is still a race condition between the watchers because there is no ordering. e.g. update 150 to prefix A happened before update 301 to prefix C but that doesn't necessarily mean the watchers fire in the same order. Network ordering issues, Goroutine scheduling issues, etc, etc all mean you cannot depend on a given ordering. 

Like I said, this is an edge case, and not something you are likely to casually experience while playing around with it. However, the problem is there nonetheless.

**Comment by cleung2010** [comment]
Got it, thanks for clearing things up!

**Comment by cleung2010** [comment]
@armon I just wanted to give an update on the PR. I've been busy lately, so I might have to put this off for the moment.

**Comment by armon** [comment]
No worries. I'm going to close this for now, but please re-open when ready.

**Pull request closed without merging**
